### ISSUE TITLE
0 keypoints detected for serveral images

### ISSUE THREAD

**Issue by LucaLovagnini** [sloup/hessgpu#1]
I've tried your hessgpu code on the [Oxford building dataset](http://www.robots.ox.ac.uk/~vgg/data/oxbuildings/) and there are many images where 0 keypoints are detected using the default settings of the bin/hess binary that you provide in your code.

I'm sending you a couple of examples where 0 descriptors are detected. As you can see, there is nothing in particular in them. Why this happens? And how can I solve this?
![oxford_003267](https://cloud.githubusercontent.com/assets/11682952/24499250/552b6382-1541-11e7-937a-42ee142e0fa1.jpg)
![magdalen_000662](https://cloud.githubusercontent.com/assets/11682952/24499278/6c8d9270-1541-11e7-842e-fca4f05e3282.jpg)

**Comment by sloup** [comment]
This happens because, by default, keypoints with hessian response higher that `0.02/3` are detected which results in zero detected keypoints for such kind of images.

You can change the threshold for hessian response (i.e. use lower value that default one) to get more keypoints by command line option  "`-t <float>`", e.g. "`-t 0.00075`" for the first image and "`-t 0.0025`" for the second one.

You can also modify directly the source code  of HessGPU/hessgpucmd.cpp by adding "`-t`" option to the command line parameters at line 33: `char *localargv[] = { "-cuda", "0", "-nogl", "-v", "1", "-t", "0.00075"};`
